### ISSUE TITLE
Changing checkbox position

### ISSUE THREAD

**Issue by imeed166** [ebullient/obsidian-snippetor#11]
Add another 2 sliders to change the X and Y of the entire checkbox (to align it with the text or to distance the checkbox from it...). 

![Screen Shot 2022-02-18 at 8 17 50 AM](https://user-images.githubusercontent.com/38974541/154636131-6daad47b-735f-48c9-a4fb-387ead621eff.jpg)

**Comment by ebullient** [comment]
This one is hard, because themes mess with this setting a lot (and it is already very different between Reading mode and Live Preview mode). I'm loathe to try to mess with this one. You can hide the border if you're using an emoji (which can visually make more room), but it will be difficult to change the position of one checkbox given how the behavior of the list overall behaves.

Have you tried editing the snippet manually to see what that looks like (and if it works) across both Reading and Live Preview modes?

**Comment by imeed166** [comment]
I just thought it would be a cool feature to have. I don't really have a problem with it. 
Thank you for the suggestion, If I ever need to change it, I'll edit the snippet manually.
